name: Lint and Commit
on: push

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: davidslusser/actions_python_ruff@v1
      with:
        options: --fix . --config=.github/workflows/.ruff.toml
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'style fixes by ruff'
